# Generated by Django 4.1.13 on 2025-02-25 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clothes',
            fields=[
                ('_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('size', models.CharField(max_length=50)),
                ('price', models.FloatField()),
                ('image_url', models.CharField(max_length=500)),
            ],
            options={
                'db_table': 'clothes',
            },
        ),
    ]
