# Generated by Django 3.1.12 on 2025-02-16 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mobile',
            name='image_url',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='mobile',
            name='price',
            field=models.FloatField(),
        ),
    ]
