# Generated by Django 4.1.13 on 2025-02-25 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('author', models.CharField(max_length=255)),
                ('price', models.FloatField()),
                ('image', models.CharField(max_length=500)),
                ('description', models.TextField()),
                ('published_date', models.DateField()),
            ],
            options={
                'db_table': 'book',
            },
        ),
    ]
