# Generated by Django 3.1.12 on 2025-02-16 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='id',
            new_name='_id',
        ),
        migrations.AlterField(
            model_name='book',
            name='image',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterModelTable(
            name='book',
            table='book',
        ),
    ]
